config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'home#index'

  resources :users, only: [:show, :edit, :update, :destroy]
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, null: false
  validates :email, null: false, uniqueness: { case_sensitive: false } # Rails 6.1のuniquenessバリデータはデフォルトで大文字小文字を区別しなくなります。
                                                                       # case_sensitiveオプションは、trueだと大文字小文字を区別する。しかし、DB側のcollationに変更がなければ、問題がある。
                                                                       # falseだと大文字小文字を区別しなくなる。しかし、大文字小文字は同じに扱われるため問題がある。
  validates :password, null: false

  def self.guest
    find_or_create_by!(email: 'guest@exapmle.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_main.html.haml
.main_wrapper
  .main_wrapper__container
    .main_wrapper__container__inner
      %h1.main_wrapper__container__inner--title
        Filmi
      %p.main_wrapper__container__inner--text
        あなたの好きな映画、テレビ番組を見つけよう!!
      .main_wrapper__container__inner__search
        = form_with do |form|
          = form.text_field :name, placeholder: '映画名や番組名で検索...', class: 'main_wrapper__container__inner__search--field'
          = form.submit '検索', class: 'main_wrapper__container__inner__search--btn'
  -# 映画館で上映中の映画
  .movie_slide
    .movie_slide__box
      .movie_slide__box--title
        劇場公開中の映画
      %ul.movie_slide__box__contents
        %li.movie_slide__box__contents__item
          aaaaa

        %li.movie_slide__box__contents__item
          aaaaa

        %li.movie_slide__box__contents__item
          aaaaa

        %li.movie_slide__box__contents__item
          aaaaa
        
        %li.movie_slide__box__contents__item
          aaaaa

        %li.movie_slide__box__contents__item
          aaaaa
  
  -# 近日公開予定の映画
  .coming_soon_movie
    .coming_soon_movie__box
      .coming_soon_movie__box--title
        近日公開予定作品
      %ul.coming_soon_movie__box__contents
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc
        %li.coming_soon_movie__box__contents__item
          ccccccc

  -# 人気の映画 見た・見たいの数が多いもの
  .popular_movie
    .popular_movie__box
      .popular_movie__box--title
        人気の映画
      %ul.popular_movie__box__contents
        %li.popular_movie__box__contents__item
          bbbbbb

        %li.popular_movie__box__contents__item
          bbbbbb

        %li.popular_movie__box__contents__item
          bbbbbb

        %li.popular_movie__box__contents__item
          bbbbbb

        %li.popular_movie__box__contents__item
          bbbbbb

        %li.popular_movie__box__contents__item
          bbbbbb
        
        %li.popular_movie__box__contents__item
          bbbbbb

  -# 高評価の映画 評価の星が多かったもの
  .high_rating_movie
    .high_rating_movie__box
      .high_rating_movie__box--title
        高評価の映画
      %ul.high_rating_movie__box__contents
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd
        %li.high_rating_movie__box__contents__item
          dddddddd

  -# カテゴリーごとに分けられている映画一覧
  -# .category_movie
  -#   .category_movie__box
  -#     .category_movie__box--title
  -#       アクション (カテゴリーごとに)
      
  -#     %ul.category_movie__box__contents
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item
  -#       %li.category_movie__box__contents__item

app/views/home/index.html.haml
- if user_signed_in?
  = render 'shares/user_header'
- else 
  = render 'shares/header'

= render 'main'

= render 'shares/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Filmi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shares/_footer.html.haml
.shares_footer
  .shares_footer__box
    2020 ©️ Filmi

app/views/shares/_header.html.haml
.shares_header
  .shares_header__box
    = link_to root_path, class: 'root_path' do
      = image_tag "filmi_素材/header_logo_icon.png", alt: 'ロゴ画像', class: 'header_logo_icon'
      Filmi

    .shares_header__box__menu
      .shares_header__box__menu__movie
        %text.pulldown_title 映画
        .pulldown
          %ul.pulldown__list
            %li.pulldown__list__item
              人気映画
            %li.pulldown__list__item
              公開中の映画
            %li.pulldown__list__item
              公開予定作品

      .shares_header__box__menu__tv
        %text.pulldown_title テレビ番組
        .pulldown.pulldown_tv
          %ul.pulldown__list
            %li.pulldown__list__item
              人気番組
            %li.pulldown__list__item
              放送中の番組

      .shares_header__box__menu__sign_up
        = link_to new_user_registration_path, class: 'link' do
          新規登録
      .shares_header__box__menu__login
        = link_to user_session_path, class: 'link' do
          ログイン
      .shares_header__box__menu__search
        = icon('fa', 'search')

app/views/shares/_user_header.html.haml
.shares_header
  .shares_header__box
    = link_to root_path, class: 'root_path' do
      = image_tag "filmi_素材/header_logo_icon.png", alt: 'ロゴ画像', class: 'header_logo_icon'
      Filmi

    .shares_header__box__menu
      .shares_header__box__menu__movie
        %text.pulldown_title 映画
        .pulldown
          %ul.pulldown__list
            %li.pulldown__list__item
              人気映画
            %li.pulldown__list__item
              公開中の映画
            %li.pulldown__list__item
              公開予定作品

      .shares_header__box__menu__tv
        %text.pulldown_title テレビ番組
        .pulldown.pulldown_tv
          %ul.pulldown__list
            %li.pulldown__list__item
              人気番組
            %li.pulldown__list__item
              放送中の番組

      .shares_header__box__menu__new
        = icon('fa', 'plus', class: 'shares_header__box__menu__new__list')

      .shares_header__box__menu__my_page
        = link_to user_path(current_user) do
          = icon('fa', 'user-circle', class: 'shares_header__box__menu__my_page__list')

      .shares_header__box__menu__logout
        = link_to destroy_user_session_path, method: :delete, class: 'link' do
          ログアウト

      .shares_header__box__menu__search
        = icon('fa', 'search')

app/views/users/_my_page.html.haml
.my_page_wrapper
  .my_page_wrapper__box
    .my_page_wrapper__box__inner
    
      = render 'my_page_list'

      .my_page_wrapper__box__inner__right
        %h1.my_page_wrapper__box__inner__right--title
          プロフィール
        
        .my_page_wrapper__box__inner__right__content

app/views/users/_my_page_list.html.haml
%ul.my_page_wrapper__box__inner__left
  %li.my_page_wrapper__box__inner__left__user
    = image_tag 'filmi_素材/Google_icon.png', class: 'my_page_wrapper__box__inner__left__user--icon'
    .my_page_wrapper__box__inner__left__user--name
      = @user.name
    .my_page_wrapper__box__inner__left__user--email
      = @user.email
          
  %li.my_page_wrapper__box__inner__left__item
    = link_to user_path, class: 'my_page_wrapper__box__inner__left__item--link' do
      = icon('fa', 'user')
      プロフィール
  %li.my_page_wrapper__box__inner__left__item
    = link_to edit_user_path, class: 'my_page_wrapper__box__inner__left__item--link' do
      = icon('fa', 'cog')
      アカウント設定
  %li.my_page_wrapper__box__inner__left__item
    = link_to '#', class: 'my_page_wrapper__box__inner__left__item--link' do
      = icon('fa', 'pen')
      レビュー・考察

app/views/users/edit.html.haml
= render 'shares/user_header'

.user_edit
  .user_edit__wrapper
    .user_edit__wrapper__inner

      = render 'my_page_list'

      .user_edit__wrapper__inner__right
        %h1.user_edit__wrapper__inner__right--title
          アカウント設定 
        = form_with model: @user, class: 'user_edit__wrapper__inner__right__form' do |f|
          .user_edit__wrapper__inner__right__form__name.user_edit__wrapper__inner__right__form__item
            = f.label 'ユーザー名', class: 'user_edit__wrapper__inner__right__form__name--title'
            = f.text_field :name, class: 'user_edit__wrapper__inner__right__form__name__field'
          .user_edit__wrapper__inner__right__form__email.user_edit__wrapper__inner__right__form__item
            = f.label 'メールアドレス', class: 'user_edit__wrapper__inner__right__form__email--title'
            = f.text_field :email, class: 'user_edit__wrapper__inner__right__form__email__field'

          = f.submit '更新', class: 'user_edit__wrapper__inner__right__form--btn'

          .user_edit__wrapper__inner__right__form__delete
            = link_to user_path(current_user), method: :delete, class: 'user_edit__wrapper__inner__right__form__delete--btn' do
              アカウント削除

= render 'shares/footer'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/shared/_login.html.haml
.shared_login
  .shared_login__box
    .shared_login__box__inner
      %h2.shared_login__box__inner--title Filmiアカウント
      = form_with(model: @user, url: user_session_path, local: true, class: 'shared_login__box__inner__form') do |f|
        .shared_login__box__inner__form__field
          = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: 'メールアドレス', class: 'shared_login__box__inner__form__field__email'
        .shared_login__box__inner__form__field
          = f.password_field :password, autocomplete: "current-password", placeholder: 'パスワード', class: 'shared_login__box__inner__form__field__password'
          .shared_login__box__inner__form__field__save
            - if devise_mapping.rememberable?
              = f.check_box :ログイン情報を保存
              = f.label :ログイン情報を保存
          = link_to "パスワードをお忘れの方", new_password_path(resource_name), class: 'shared_login__box__inner__form__field__forget_password'
        = f.submit "ログイン", class: 'shared_login__box__inner__form--submit'
        -# ゲストログイン用
        = link_to users_guest_sign_in_path, method: :post, class: 'shared_login__box__inner__form--guest_submit' do
          ゲストログイン
      
        .shared_login__box__inner__form__under_nav
          .shared_login__box__inner__form__under_nav--sign_up
            アカウントをお持ちでない方はこちら ➡︎
            = link_to "新規登録", new_registration_path(resource_name)
            
      = render 'users/shared/sns_login'

app/views/users/shared/_sign_up.html.haml
.shared_sign_up 
  .shared_sign_up__box
    .shared_sign_up__box__inner
      %h2.shared_sign_up__box__inner--title Filmiアカウントの作成

      = render 'users/shared/sns_sign_up'
      
      = form_with(model: @user, url: user_registration_path, local: true, class: 'shared_sign_up__box__inner__form') do |f|
        = render "users/shared/error_messages", resource: resource
        .shared_sign_up__box__inner__form__field
          お名前
          = f.text_field :name,  autocomplete: 'name', class: 'shared_sign_up__box__inner__form__field__new_name'
        .shared_sign_up__box__inner__form__field
          メールアドレス
          = f.email_field :email, autofocus: true, autocomplete: "email", class: 'shared_sign_up__box__inner__form__field__new_email'
        .shared_sign_up__box__inner__form__field
          パスワード
          = f.password_field :password, autocomplete: "new-password", placeholder: @minimum_password_length.to_s + '文字以上入力してください', class: 'shared_sign_up__box__inner__form__field__new_password'
        .shared_sign_up__box__inner__form__field
          パスワードを再入力
          = f.password_field :password_confirmation, autocomplete: "new-password", class: 'shared_sign_up__box__inner__form__field__new_password'
        %hr.sign_up_line
        = f.submit '新規登録', class: 'shared_sign_up__box__inner__form--submit'
        -# ゲストログイン用
        = link_to users_guest_sign_in_path, method: :post, class: 'shared_sign_up__box__inner__form--guest_submit' do
          ゲストログイン
        .shared_sign_up__box__inner__form__under_nav
          = link_to user_session_path, class: 'shared_sign_up__box__inner__form__under_nav--login' do
            アカウントをお持ちの方

app/views/users/shared/_sns_login.html.haml
.shared_login__box__inner--text
  または
.shared_login__box__inner__login_sns
  .shared_login__box__inner__login_sns--title 
    他のアカウントでかんたんにログイン
  %ul.shared_login__box__inner__login_sns__ul
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--twitter' do
        = icon('fab', 'twitter', class: 'sns_login_icon')
        Twitter
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--google' do
        = image_tag 'filmi_素材/Google_icon.png', class: 'sns_login_icon'
        Google
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--apple' do
        = icon('fab', 'apple', class: "sns_login_icon")
        Apple

app/views/users/shared/_sns_sign_up.html.haml
.shared_login__box__inner__login_sns
  .shared_login__box__inner__login_sns--title 
    次のアカウントをお持ちの方は簡単にFilmiアカウントを作成できます
  %ul.shared_login__box__inner__login_sns__ul
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--twitter' do
        = icon('fab', 'twitter', class: 'sns_login_icon')
        Twitter
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--google' do
        = image_tag 'filmi_素材/Google_icon.png', class: 'sns_login_icon'
        Google
    %li.shared_login__box__inner__login_sns__ul__li
      = link_to '#', class: 'shared_login__box__inner__login_sns__ul__li--apple' do
        = icon('fab', 'apple', class: "sns_login_icon")
        Apple
.shared_login__box__inner--text
  上記のアカウントをお持ちでない方は以下をご記入ください

app/views/users/show.html.haml
= render 'shares/user_header'

= render 'my_page'

= render 'shares/footer'